"""One-time import of `routine_seed.json` into a fresh Avery database.

Run once, against the new deployment, after the account that will own the data
exists:

    python -m seeds.import_seed --user-id 1 [--seed seeds/routine_seed.json]

What it does NOT do, on purpose:

- It does not create the user. The owner has to sign up through the normal flow
  so the password hash / OAuth identity is real; a seeded user would be an
  account nobody can log into.
- It does not import events. Events are regenerated by materializing the
  routine, and importing a month of stale slots would collide with whatever the
  new deployment generates.
- It does not import tokens, sessions or calendar connections. Those are
  credentials bound to a machine and an OAuth consent; they must be granted
  again on the new host, not copied.

Idempotence: refuses to run if the target user already owns tags or routines,
rather than silently doubling them. Pass --force to import anyway.
"""

from __future__ import annotations

import argparse
import asyncio
import json
from datetime import datetime, time
from pathlib import Path

from sqlalchemy import func, select, text

from app.database import SessionLocal
from app.models import Routine, RoutineBlock, Rule, Tag

SEED_DEFAULT = Path(__file__).parent / "routine_seed.json"


def _time(raw: str) -> time:
    """'08:00:00.000000' -> time(8, 0). SQLite stores Time as text with a
    microsecond tail that `time.fromisoformat` handles, but older exports may
    not carry one."""
    return time.fromisoformat(raw)


def _dt(raw: str | None) -> datetime | None:
    return datetime.fromisoformat(raw) if raw else None


def _json(raw):
    """Columns declared as JSON come back as text from a raw sqlite3 export but
    as real lists when SQLAlchemy loaded them. Accept both."""
    return json.loads(raw) if isinstance(raw, str) else raw


async def run(seed_path: Path, user_id: int, force: bool) -> None:
    seed = json.loads(seed_path.read_text(encoding="utf-8"))

    async with SessionLocal() as session:
        existing = await session.scalar(
            select(func.count()).select_from(Tag).where(Tag.user_id == user_id)
        )
        existing_routines = await session.scalar(
            select(func.count()).select_from(Routine).where(Routine.user_id == user_id)
        )
        if (existing or existing_routines) and not force:
            raise SystemExit(
                f"user {user_id} already has {existing} tags and {existing_routines} "
                f"routines. Importing would duplicate them. Re-run with --force if "
                f"that is really what you want."
            )

        # Tags first: routine blocks and rules both reference tag ids, and the
        # seed preserves those ids precisely so the references survive.
        for t in seed["tags"]:
            session.add(
                Tag(
                    id=t["id"], user_id=user_id, name=t["name"], color=t["color"],
                    icon=t.get("icon"), sort_order=t.get("sort_order", 0),
                    archived=bool(t.get("archived", 0)),
                    description=t.get("description") or "",
                )
            )

        for r in seed["routines"]:
            session.add(
                Routine(
                    id=r["id"], user_id=user_id, name=r["name"], note=r.get("note", ""),
                    is_active=bool(r.get("is_active", 0)),
                    created_at=_dt(r.get("created_at")) or datetime.now(),
                    updated_at=_dt(r.get("updated_at")) or datetime.now(),
                )
            )
        await session.flush()  # routines must exist before their blocks reference them

        for b in seed["routine_blocks"]:
            session.add(
                RoutineBlock(
                    id=b["id"], routine_id=b["routine_id"], days=_json(b["days"]),
                    start_time=_time(b["start_time"]), end_time=_time(b["end_time"]),
                    task_name=b["task_name"], tag_ids=_json(b["tag_ids"]),
                    sort_order=b.get("sort_order", 0),
                )
            )

        for r in seed["rules"]:
            session.add(
                Rule(
                    id=r["id"], user_id=user_id, name=r["name"], groups=_json(r["groups"]),
                    tolerance=r["tolerance"], exclude_tag_ids=_json(r["exclude_tag_ids"]),
                    effective_from=_dt(r["effective_from"]),
                    effective_to=_dt(r.get("effective_to")),
                    note=r.get("note", ""),
                    created_at=_dt(r.get("created_at")) or datetime.now(),
                )
            )

        await session.commit()

        # Postgres keeps each table's id sequence independent of explicitly
        # inserted ids, so after seeding rows 1..8 the sequence still hands out
        # 1 next and the user's very first "new tag" dies on a duplicate key.
        # SQLite has no such object and needs nothing here -- which is exactly
        # why this stayed invisible until the import ran on real Postgres.
        if session.bind.dialect.name == "postgresql":
            for table in ("tags", "routines", "routine_blocks", "rules"):
                await session.execute(
                    text(
                        f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                        f"COALESCE((SELECT MAX(id) FROM {table}), 1))"
                    )
                )
            await session.commit()
            print("  advanced Postgres id sequences past the seeded rows")

    print(
        f"imported: {len(seed['tags'])} tags, {len(seed['routines'])} routines, "
        f"{len(seed['routine_blocks'])} blocks, {len(seed['rules'])} rules "
        f"-> user {user_id}"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seed", type=Path, default=SEED_DEFAULT)
    ap.add_argument("--user-id", type=int, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    asyncio.run(run(args.seed, args.user_id, args.force))


if __name__ == "__main__":
    main()
